name: Launch EC2 Instance

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  launch-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 Instance
      run: |
        aws ec2 run-instances \
          --image-id ami-020cba7c55df1f615 \
          --instance-type t2.micro \
          --key-name vv \
          --security-groups my-security-group \
          --count 1 \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub-Launch-Instance}]'
