name: Launch EC2 Instance

on:
  workflow_dispatch:

jobs:
  launch-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0f918f7e67a3323f0 \
          --instance-type t2.micro \
          --key-name vv \
          --security-group-ids sg-0123456789abcdef0 \
          --subnet-id subnet-0123456789abcdef0 \
          --count 1 \
          --associate-public-ip-address \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub-Launch-Instance}]'
